### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by joefulton** [R-MAN-D/magento-custom-discount-store-credit-module#1]
Hi, I tried your module but some files seems to be missing as referenced in storecredit.xml

**Comment by R-MAN-D** [comment]
Hello Joe, what does the error message says? (Note: Don't forget as well to clear your cache)

**Comment by joefulton** [comment]
I'm not getting any errors. It's just when I click the link "My Store Credit History" in the customer account it's just a blank page. When I click on the link I get an error **include(): Filename cannot be empty** and **include(): Failed opening '' for inclusion**. I think those errors are because there are some files missing : ) Thanks for writing back

**Comment by R-MAN-D** [comment]
May I know the version of Magento that you are using? Thanks!

**Comment by joefulton** [comment]
I'm using Magento ver. 1.9.2.4

**Comment by joefulton** [comment]
```
    <reference name="content">
        <block type="core/template" name="storecredit_history" template="storecredit/history.phtml" /> <!-- app/design/frontend/[theme]/default/template/storecredit/history.phtml -->
        <block type="customer/account_dashboard" name="customer.account.link.back" template="customer/account/link/back.phtml" />
    </reference>
```

history.phtml isn't there. The back link shows thou.

**Comment by R-MAN-D** [comment]
Please do create that file at app/design/frontend/**[theme]**/default/template/storecredit/history.phtml or app/design/frontend/**rwd**/default/template/storecredit/history.phtml. Leave it empty for now. (Note: Depending on which theme you are currently on)

**Comment by joefulton** [comment]
Okay

**Comment by R-MAN-D** [comment]
Hi Joe, I just updated the README file by the way. You can see the DB structure from there as well.

**Comment by joefulton** [comment]
Actually I have already created the database tables but I went ahead and recreated them from the query you have. Still the same results. Thanks

**Comment by shajikninan** [comment]
Please give me frontend phtml files

**Comment by Jeeva-Rathinam** [comment]
After install how will be reflect on website customer account page.

**Comment by Chandan8050** [comment]
HI everyone,

It is possible to share anyone history.phtml and storecredit.phtml file.
